// Auto-generated by scripts/generate-page-modules.mjs
export const GENERATED_PLAN_ROUTE_TREE = [
  {
    "name": "studioWorkspace",
    "text": "应用装配中心",
    "router": "/studio",
    "meta": {
      "iconName": "icon-menu2level",
      "title": "应用装配中心",
      "description": "",
      "menuAlive": "studioWorkspace"
    },
    "children": [
      {
        "name": "studioDemoWorkspace",
        "text": "演示工作区",
        "router": "/demo/workspace",
        "meta": {
          "iconName": "icon-menu2level",
          "title": "演示工作区",
          "description": "展示装配应用如何承载定制体验的示例工作区。",
          "menuAlive": "demoWorkspace"
        },
        "component": "@/page-demo-workspace/index.vue"
      },
      {
        "name": "appManagement",
        "text": "业务应用",
        "router": "/studio/apps",
        "meta": {
          "iconName": "icon-menu2level",
          "title": "业务应用",
          "description": "管理可复用的业务应用定义、运行形态和交付目标。",
          "menuAlive": "appManagement"
        },
        "component": "@/page-studio-apps/index.vue"
      },
      {
        "name": "pageManagement",
        "text": "页面能力库",
        "router": "/studio/pages",
        "meta": {
          "iconName": "icon-menu2level",
          "title": "页面能力库",
          "description": "维护可复用页面资产、归属、分类和引用关系。",
          "menuAlive": "pageManagement"
        },
        "component": "@/page-studio-pages/index.vue"
      },
      {
        "name": "menuManagement",
        "text": "导航方案",
        "router": "/studio/schemes",
        "meta": {
          "iconName": "icon-menu2level",
          "title": "导航方案",
          "description": "装配导航树，并将可复用页面绑定到交付方案中。",
          "menuAlive": "menuManagement"
        },
        "component": "@/page-studio-schemes/index.vue"
      }
    ]
  }
];
