// Auto-generated by scripts/generate-page-modules.mjs
export const GENERATED_PAGE_MODULES = {
  '../../../../packages/page-demo-dashboard/src/index.vue': () => import('../../../../packages/page-demo-dashboard/src/index.vue'),
  '../../../../packages/page-demo-workspace/src/index.vue': () => import('../../../../packages/page-demo-workspace/src/index.vue'),
  '../../../../packages/page-login/src/index.vue': () => import('../../../../packages/page-login/src/index.vue'),
  '../../../../packages/page-studio-apps/src/index.vue': () => import('../../../../packages/page-studio-apps/src/index.vue'),
  '../../../../packages/page-studio-pages/src/index.vue': () => import('../../../../packages/page-studio-pages/src/index.vue'),
  '../../../../packages/page-studio-schemes/src/index.vue': () => import('../../../../packages/page-studio-schemes/src/index.vue'),
};
