// Auto-generated by scripts/generate-page-modules.mjs
export const GENERATED_PLAN_ROUTE_TREE = [
  {
    "name": "demoSolution",
    "text": "演示方案",
    "router": "/demo",
    "meta": {
      "iconName": "icon-menu2level",
      "title": "演示方案",
      "description": "",
      "menuAlive": "demoSolution"
    },
    "children": [
      {
        "name": "demoDashboard",
        "text": "演示看板",
        "router": "/demo/dashboard",
        "meta": {
          "iconName": "icon-menu2level",
          "title": "演示看板",
          "description": "用于展示框架能力的轻量演示看板。",
          "menuAlive": "demoDashboard"
        },
        "component": "@/page-demo-dashboard/index.vue"
      },
      {
        "name": "demoWorkspace",
        "text": "演示工作区",
        "router": "/demo/workspace",
        "meta": {
          "iconName": "icon-menu2level",
          "title": "演示工作区",
          "description": "展示装配应用如何承载定制体验的示例工作区。",
          "menuAlive": "demoWorkspace"
        },
        "component": "@/page-demo-workspace/index.vue"
      }
    ]
  }
];
